/*
 * PosJApplet.java
 *
 * Created on July 11, 2004, 2:50 PM
 */

package com.inexum.util.pos;

/**
 *
 * @author  inexum
 */
public class PosJApplet extends javax.swing.JApplet {
    
    /** Creates new form PosJApplet */
    public PosJApplet() {
        initComponents();
        mPos = new Pos();
        jTextPos.setText(mPos.initMessage());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButtonChq = new javax.swing.JButton();
        jButtonMac = new javax.swing.JButton();
        jButtonSav = new javax.swing.JButton();
        jButtonCorrect = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jButtonOK = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jTextPos = new javax.swing.JTextArea();
        jButtonDot = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextCardNumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextExpDate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextName = new javax.swing.JTextField();
        jButtonSwipe = new javax.swing.JButton();

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });

        jPanel1.add(jButton0, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        jButtonChq.setText("Chq");
        jButtonChq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChqActionPerformed(evt);
            }
        });

        jPanel1.add(jButtonChq, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jButtonMac.setText("mAc");
        jButtonMac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMacActionPerformed(evt);
            }
        });

        jPanel1.add(jButtonMac, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jButtonSav.setText("Sav");
        jButtonSav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSavActionPerformed(evt);
            }
        });

        jPanel1.add(jButtonSav, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        jButtonCorrect.setForeground(new java.awt.Color(204, 153, 0));
        jButtonCorrect.setText("Correct");
        jButtonCorrect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCorrectActionPerformed(evt);
            }
        });

        jPanel1.add(jButtonCorrect, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        jButtonCancel.setForeground(new java.awt.Color(204, 0, 0));
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jPanel1.add(jButtonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        jButtonOK.setForeground(new java.awt.Color(0, 102, 102));
        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jPanel1.add(jButtonOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.add(jTextPos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 280, 50));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 60));

        jButtonDot.setText(".");
        jButtonDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDotActionPerformed(evt);
            }
        });

        jPanel1.add(jButtonDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        getContentPane().add(jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setText("Card Number:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTextCardNumber.setText("1234567890123456");
        jPanel3.add(jTextCardNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 130, -1));

        jLabel2.setText("Exp. Date:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jTextExpDate.setText("0905");
        jPanel3.add(jTextExpDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 70, -1));

        jLabel3.setText("Name:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jTextName.setText("Nebojsa Vojinovic");
        jPanel3.add(jTextName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 130, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 130));

        jButtonSwipe.setForeground(new java.awt.Color(0, 51, 153));
        jButtonSwipe.setText("<< Swipe >>");
        jButtonSwipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSwipeActionPerformed(evt);
            }
        });

        jPanel2.add(jButtonSwipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        getContentPane().add(jPanel2);

    }//GEN-END:initComponents

    private void jButtonDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDotActionPerformed
        jTextPos.append(".");
    }//GEN-LAST:event_jButtonDotActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        jTextPos.append("0");
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        jTextPos.append("9");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jTextPos.append("8");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jTextPos.append("7");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jTextPos.append("6");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jTextPos.append("5");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTextPos.append("3");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTextPos.append("3");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextPos.append("2");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextPos.append("1");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonSwipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSwipeActionPerformed
        Card card = new Card(jTextCardNumber.getText(), jTextExpDate.getText(),
                                jTextName.getText());
        mPreText = mPos.swiped(card);
        jTextPos.setText(mPreText);        
    }//GEN-LAST:event_jButtonSwipeActionPerformed

    private void jButtonCorrectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCorrectActionPerformed
        jTextPos.setText(mPos.cancelTransaction());
    }//GEN-LAST:event_jButtonCorrectActionPerformed

    private void jButtonSavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSavActionPerformed
        jTextPos.setText(mPos.savTransaction());
    }//GEN-LAST:event_jButtonSavActionPerformed

    private void jButtonChqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChqActionPerformed
        jTextPos.setText(mPos.chqTransaction());
    }//GEN-LAST:event_jButtonChqActionPerformed

    private void jButtonMacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMacActionPerformed
        jTextPos.setText(mPos.mAcTransaction());
    }//GEN-LAST:event_jButtonMacActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        jTextPos.setText(
            mPos.okProcessing(jTextPos.getText().substring(mPreText.length())));
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        jTextPos.setText(mPos.cancelTransaction());
    }//GEN-LAST:event_jButtonCancelActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton0;
    private javax.swing.JTextField jTextExpDate;
    private javax.swing.JButton jButtonMac;
    private javax.swing.JButton jButtonDot;
    private javax.swing.JTextField jTextName;
    private javax.swing.JButton jButtonSwipe;
    private javax.swing.JTextArea jTextPos;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonChq;
    private javax.swing.JTextField jTextCardNumber;
    private javax.swing.JButton jButtonCorrect;
    private javax.swing.JButton jButtonSav;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    private Pos    mPos;
    private String mPreText;
}
