/*
 * LoginDialog.java
 *
 * Created on July 17, 2001, 12:23 PM
 */

package com.inexum.demo.MicroAc.Wallet;

import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author  rgoold
 * @version 
 */
public class LoginDialog extends javax.swing.JDialog
{
    private StringBuffer    m_name;
    private StringBuffer    m_password;
    
    /** Creates new form LoginDialog */
    public LoginDialog (java.awt.Frame parent, boolean modal,
        StringBuffer name, StringBuffer password)
    {
        super(parent, modal);
        m_name = name;
        m_password = password;
        initComponents();
        /*
         * On Mandrake 8, we found putting a setResizable(false) actually
         * prevented the code from resizing the window as well, and Forte
         * only generates the resizing code after the setResizable option.
         * As a work around, setResizable is called here instead.
         */
        setResizable(false);
        getRootPane().setDefaultButton(m_okButton);
        getRootPane().registerKeyboardAction(
            new ActionListener()
            {
                public void actionPerformed (ActionEvent event)
                {
                    m_cancelButton.doClick();
                }
            },
            KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0),
            JComponent.WHEN_IN_FOCUSED_WINDOW);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        m_loginField = new javax.swing.JTextField();
        m_passwordField = new javax.swing.JPasswordField();
        m_cancelButton = new javax.swing.JButton();
        m_okButton = new javax.swing.JButton();
        
        getContentPane().setLayout(null);
        
        setTitle("Login");
        setModal(true);
        setFont(new java.awt.Font("Arial", 0, 12));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        
        jLabel3.setText("Login:");
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setFont(new java.awt.Font("Arial", 0, 11));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 10, 70, 20);
        
        jLabel4.setText("Password:");
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setFont(new java.awt.Font("Arial", 0, 11));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 40, 70, 20);
        
        m_loginField.setFont(new java.awt.Font("Arial", 0, 11));
        m_loginField.setNextFocusableComponent(m_passwordField);
        getContentPane().add(m_loginField);
        m_loginField.setBounds(80, 10, 120, 20);
        
        m_passwordField.setFont(new java.awt.Font("Courier New", 0, 11));
        m_passwordField.setNextFocusableComponent(m_cancelButton);
        getContentPane().add(m_passwordField);
        m_passwordField.setBounds(80, 40, 120, 20);
        
        m_cancelButton.setFont(new java.awt.Font("Arial", 0, 11));
        m_cancelButton.setText("Cancel");
        m_cancelButton.setDefaultCapable(false);
        m_cancelButton.setNextFocusableComponent(m_okButton);
        m_cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_cancelButtonActionPerformed(evt);
            }
        });
        
        getContentPane().add(m_cancelButton);
        m_cancelButton.setBounds(10, 70, 70, 20);
        
        m_okButton.setFont(new java.awt.Font("Arial", 0, 11));
        m_okButton.setText("OK");
        m_okButton.setNextFocusableComponent(m_loginField);
        m_okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_okButtonActionPerformed(evt);
            }
        });
        
        getContentPane().add(m_okButton);
        m_okButton.setBounds(130, 70, 70, 20);
        
        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setSize(new java.awt.Dimension(220, 120));
        setLocation((screenSize.width-220)/2,(screenSize.height-120)/2);
    }//GEN-END:initComponents

  private void m_okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_okButtonActionPerformed
        if (m_name != null)
        {
            m_name.setLength(0);
            m_name.append(m_loginField.getText());
        }
        
        if (m_password != null)
        {
            m_password.setLength(0);
            m_password.append(m_passwordField.getPassword());
        }
        
        closeDialog(new java.awt.event.WindowEvent(this,
            java.awt.event.WindowEvent.WINDOW_CLOSING));
  }//GEN-LAST:event_m_okButtonActionPerformed

  private void m_cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_cancelButtonActionPerformed
        if (m_name != null)
        {
            m_name.setLength(0);
        }
        if (m_password != null)
        {
            m_password.setLength(0);
        }
        
        closeDialog(new java.awt.event.WindowEvent(this,
            java.awt.event.WindowEvent.WINDOW_CLOSING));
  }//GEN-LAST:event_m_cancelButtonActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**
    * @param args the command line arguments
    */
    public static void main (String args[])
    {
        StringBuffer name = new StringBuffer();
        StringBuffer password = new StringBuffer();
        new LoginDialog(new javax.swing.JFrame(), true, name, password).show();
        System.out.println("    Name: " + name.toString());
        System.out.println("Password: " + password.toString());
        System.exit(0);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField m_loginField;
    private javax.swing.JPasswordField m_passwordField;
    private javax.swing.JButton m_cancelButton;
    private javax.swing.JButton m_okButton;
    // End of variables declaration//GEN-END:variables

}

